name: position
description: A new Flutter project demo.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  workmanager: ^0.5.1
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.19
  google_fonts: ^4.0.3
  supercharged: ^2.1.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  rxdart: ^0.27.7
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  location: ^4.4.0
  background_locator_2: ^2.0.6
  google_maps_flutter: ^2.2.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/sbs-group.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pcc.png"
  min_sdk_android: 16 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/img/
